# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Jorge Avila Cartes
# Description of the Site
description: Ph.D. student in Bioinformati[c.s.]
# URL of Image of the Site
site-image: /blog/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/640781/pexels-photo-640781.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: jorgeavilacartes@gmail.com
facebook_username: 
twitter_username: javilac1
instagram_username: 
linkedin_username: jorgeavilacartes
github_username:  jorgeavilacartes
youtube_channel_id: UC_aLhhO-GfYWRMIbrNsctKw
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: G-2WXVYX5C08

# Disqus
disqus-shortname: jorgeavilacartes

# Name of the Author
author-name: Jorge Avila Cartes
# URL for the Image of the Author
author-image: https://media-exp1.licdn.com/dms/image/C5603AQHlwTB9ODAcsA/profile-displayphoto-shrink_800_800/0/1629928510080?e=1667433600&v=beta&t=3easV1LQLBERDKDNkeNLY3cFYDXQbVfm7U4OV8HD40Q
# 60 Words About the Author
author-about: Hi there, I am a Ph.D. student in CS, working on Pangenomics as part of the <a href="https://alpaca-itn.eu/" target="_blank">ALPACA project</a>, at the University of Milano-Bicocca, Italy. I love good food and coffee.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/jorgeavilacartes

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
